name: raterestro
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
    fluttertoast: ^3.1.3
    url_launcher: ^5.4.1
    firebase_messaging: ^6.0.9
    image_picker: ^0.6.3
    flutter_datetime_picker: ^1.3.0
    shared_preferences: ^0.5.6
    firebase_auth:
    cloud_firestore: ^0.12.9+5
    google_maps_flutter: ^0.5.20+2
    intl: ^0.16.0
    flutter_native_image:
    uuid:
    connectivity:
    firebase_storage:
    location: ^2.3.5
    scoped_model:
    rxdart: ^0.22.4
    geoflutterfire: ^2.0.3+5
    flutter_rating_bar: ^3.0.1+1

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/title_icon.jpg
        - assets/img/marker.png
        - assets/img/cash.png
        - assets/img/pay_pickup.png

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Thin.ttf
                weight: 100
              - asset: assets/fonts/Poppins-ExtraLight.ttf
                weight: 200
              - asset: assets/fonts/Poppins-Light.ttf
                weight: 300
              - asset: assets/fonts/Poppins-Regular.ttf
                weight: 400
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700
              - asset: assets/fonts/Poppins-ExtraBold.ttf
                weight: 800
              - asset: assets/fonts/Poppins-Black.ttf
                weight: 900
